[versions]
"0.3.0" = { created_at = 2022-03-13T07:03:01.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.3.0", prerelease = true }
"0.3.2" = { created_at = 2022-03-16T18:25:59.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.3.2", prerelease = true }
"0.3.3" = { created_at = 2022-03-16T19:20:52.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.3.3", prerelease = true }
"0.4.0" = { created_at = 2022-04-03T06:35:15.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.4.0", prerelease = true }
"0.5.1" = { created_at = 2022-10-18T05:00:29.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.5.1" }
"0.6.0" = { created_at = 2022-12-05T18:38:56.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.6.0" }
"0.6.1" = { created_at = 2022-12-06T04:50:48.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.6.1" }
"0.7.0" = { created_at = 2023-02-16T20:50:52.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.7.0" }
"0.8.0" = { created_at = 2023-07-16T20:40:24.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2023-09-06T17:57:57.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.9.0" }
"0.10.0" = { created_at = 2023-10-04T23:45:45.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.10.0" }
"0.11.0" = { created_at = 2023-11-01T18:08:44.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.11.0" }
"0.12.0" = { created_at = 2023-12-05T23:45:16.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.12.0" }
"0.13.0" = { created_at = 2024-01-04T02:05:30.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.13.0" }
"0.14.0" = { created_at = 2024-02-07T23:43:04.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.14.0" }
"0.15.0" = { created_at = 2024-03-06T22:10:58.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.15.0" }
"0.15.1" = { created_at = 2024-03-07T04:35:38.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.15.1" }
"0.16.0" = { created_at = 2024-04-03T19:46:23.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.16.0" }
"0.17.0" = { created_at = 2024-05-01T17:10:01.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.17.0" }
"0.17.1" = { created_at = 2024-05-07T15:39:54.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.17.1" }
"0.18.0" = { created_at = 2024-06-06T10:46:55.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.18.0" }
"0.19.0" = { created_at = 2024-07-03T21:37:40.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.19.0" }
"0.20.0" = { created_at = 2024-08-07T17:20:21.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.20.0" }
"0.21.0" = { created_at = 2024-09-04T17:11:13.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.21.0" }
"0.22.0" = { created_at = 2024-10-02T17:25:20.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.22.0" }
"0.23.0" = { created_at = 2024-11-07T04:51:38.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.23.0" }
"0.24.0" = { created_at = 2024-12-04T20:46:44.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.24.0" }
"0.25.0" = { created_at = 2025-01-02T03:57:32.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.25.0" }
"0.26.0" = { created_at = 2025-02-06T01:32:40.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.26.0" }
"0.27.0" = { created_at = 2025-03-05T23:48:50.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.27.0" }
"0.28.0" = { created_at = 2025-04-02T23:52:10.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.28.0" }
"0.28.1" = { created_at = 2025-04-05T03:45:18.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.28.1" }
"0.28.2" = { created_at = 2025-04-07T15:42:32.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.28.2" }
"0.29.0" = { created_at = 2025-05-07T17:07:16.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.29.0" }
"0.30.0" = { created_at = 2025-06-04T14:01:13.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.30.0" }
"0.31.0" = { created_at = 2025-07-02T19:41:10.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.31.0" }
"0.32.0" = { created_at = 2025-08-06T16:36:14.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.32.0" }
"0.33.0" = { created_at = 2025-09-04T02:53:09.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.33.0" }
"0.34.0" = { created_at = 2025-10-01T23:09:57.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.34.0" }
"0.35.0" = { created_at = 2025-11-06T02:22:19.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.35.0" }
"0.36.0" = { created_at = 2025-12-04T06:23:34.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.36.0" }
"0.37.0" = { created_at = 2026-01-08T00:42:03.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.37.0" }
"0.38.0" = { created_at = 2026-02-05T07:31:10.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.38.0" }
"0.39.0" = { created_at = 2026-03-04T17:59:55.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.39.0" }
"0.40.0" = { created_at = 2026-04-02T04:50:55.000Z, release_url = "https://github.com/jj-vcs/jj/releases/tag/v0.40.0" }
