[versions]
"1.0.0.Alpha1" = { created_at = 2021-12-19T13:20:44.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Alpha1" }
"1.0.0.Alpha2" = { created_at = 2021-12-19T16:06:44.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Alpha2" }
"1.0.0.Alpha3" = { created_at = 2021-12-22T09:52:00.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Alpha3" }
"1.0.0.Alpha4" = { created_at = 2021-12-22T12:43:19.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Alpha4" }
"1.0.0.Alpha5" = { created_at = 2021-12-22T14:04:42.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Alpha5" }
"1.0.0.Beta1" = { created_at = 2022-12-12T16:10:29.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Beta1" }
"1.0.0.Beta2" = { created_at = 2023-01-21T22:50:52.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Beta2" }
"1.0.0.Beta3" = { created_at = 2023-01-22T08:16:53.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.Beta3" }
"1.0.0.CR1" = { created_at = 2023-08-04T12:43:48.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.CR1" }
"1.0.0.CR2" = { created_at = 2024-01-18T20:07:47.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.CR2" }
"1.0.0.CR3" = { created_at = 2024-01-19T09:23:17.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.CR3" }
"1.0.0.CR4" = { created_at = 2024-11-09T22:26:18.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/v1.0.0.CR4" }
"1.0.0-early-access" = { created_at = 2025-06-26T09:53:22.000Z, release_url = "https://github.com/kcctl/kcctl/releases/tag/1.0.0-early-access", prerelease = true }
