[versions]
"0.6.4" = { created_at = 2019-06-18T19:12:01.000Z, release_url = "https://github.com/chmln/sd/releases/tag/0.6.4" }
"0.6.5" = { created_at = 2019-06-19T02:57:45.000Z, release_url = "https://github.com/chmln/sd/releases/tag/0.6.5" }
"0.7.2" = { created_at = 2020-03-31T19:48:20.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v0.7.2" }
"0.7.3" = { created_at = 2020-04-11T19:04:23.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v0.7.3" }
"0.7.4" = { created_at = 2020-04-22T20:55:14.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v0.7.4" }
"0.7.5" = { created_at = 2020-05-04T20:51:20.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v0.7.5" }
"0.7.6" = { created_at = 2020-08-01T02:53:24.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v0.7.6" }
"1.0.0-alpha.0" = { created_at = 2023-10-28T20:13:54.000Z, release_url = "https://github.com/chmln/sd/releases/tag/1.0.0-alpha.0", prerelease = true }
"1.0.0-pre-alpha.5" = { created_at = 2023-10-28T20:13:54.000Z, release_url = "https://github.com/chmln/sd/releases/tag/1.0.0-pre-alpha.5", prerelease = true }
"1.0.0-beta.0" = { created_at = 2023-11-05T19:18:23.000Z, release_url = "https://github.com/chmln/sd/releases/tag/1.0.0-beta.0", prerelease = true }
"1.0.0" = { created_at = 2023-11-08T02:19:46.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v1.0.0" }
"1.1.0" = { created_at = 2026-02-25T12:55:11.000Z, release_url = "https://github.com/chmln/sd/releases/tag/v1.1.0" }
