[versions]
"0.23.1" = { created_at = 2022-09-28T11:40:21.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.23.1" }
"0.24.0" = { created_at = 2023-01-27T12:37:32.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.24.0" }
"0.25.0" = { created_at = 2023-06-16T14:36:12.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.25.0" }
"0.26.0" = { created_at = 2023-08-07T13:59:36.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.26.0" }
"0.27.1" = { created_at = 2024-05-28T13:05:56.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.27.1" }
"0.28.0" = { created_at = 2024-07-30T05:46:28.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.28.0" }
"0.28.1" = { created_at = 2024-09-03T09:08:47.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.28.1" }
"0.28.2" = { created_at = 2024-09-06T08:44:37.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.28.2" }
"0.28.3" = { created_at = 2024-10-01T10:21:52.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.28.3" }
"0.28.4" = { created_at = 2024-10-15T05:52:25.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.28.4" }
"0.29.0" = { created_at = 2024-11-06T14:04:31.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.29.0" }
"0.30.0" = { created_at = 2024-11-22T07:53:07.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.30.0" }
"0.30.1" = { created_at = 2024-11-26T15:25:07.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.30.1" }
"0.30.2" = { created_at = 2024-12-02T11:41:45.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.30.2" }
"0.31.0" = { created_at = 2024-12-16T09:45:23.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.31.0" }
"0.31.1" = { created_at = 2025-01-02T10:26:41.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.31.1" }
"0.31.2" = { created_at = 2025-01-21T09:01:10.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.31.2" }
"0.31.3" = { created_at = 2025-03-10T12:20:31.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.31.3" }
"0.32.0" = { created_at = 2025-04-23T15:31:35.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.32.0" }
"0.33.0" = { created_at = 2025-06-25T13:17:38.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.33.0" }
"0.34.0" = { created_at = 2025-08-29T08:12:40.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.34.0" }
"0.34.1" = { created_at = 2025-09-01T07:14:43.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.34.1" }
"0.35.0" = { created_at = 2025-09-10T14:55:03.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.35.0" }
"0.36.0" = { created_at = 2025-11-10T11:02:21.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.36.0" }
"0.36.1" = { created_at = 2025-11-17T18:22:54.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.36.1" }
"0.36.2" = { created_at = 2025-11-25T14:56:18.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.36.2" }
"0.36.3" = { created_at = 2026-01-15T08:36:09.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.36.3" }
"0.36.4" = { created_at = 2026-03-31T18:53:07.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.36.4" }
"0.37.0" = { created_at = 2026-04-09T19:13:04.000Z, release_url = "https://github.com/grafana/tanka/releases/tag/v0.37.0" }
