[versions]
"0.1.0" = { created_at = 2019-06-17T09:22:10.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.1.0" }
"0.1.1" = { created_at = 2019-06-19T09:29:56.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.1.1" }
"0.1.2" = { created_at = 2019-06-19T13:32:16.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.1.2" }
"0.2.0" = { created_at = 2019-07-30T11:49:58.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.2.0" }
"0.2.1" = { created_at = 2019-08-08T12:50:06.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.2.1" }
"0.2.2" = { created_at = 2019-08-13T10:04:27.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.2.2" }
"0.3.0" = { created_at = 2019-09-03T07:37:05.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.3.0" }
"0.3.1" = { created_at = 2019-09-04T13:28:59.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.3.1" }
"0.4.0" = { created_at = 2019-09-26T09:15:28.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.4.0" }
"0.5.0" = { created_at = 2019-11-08T09:56:43.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.5.0" }
"0.5.1" = { created_at = 2019-11-22T10:27:54.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.5.1" }
"0.6.0" = { created_at = 2019-12-11T17:21:36.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.6.0" }
"0.7.0" = { created_at = 2020-02-03T14:02:55.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.7.0" }
"0.7.1" = { created_at = 2020-02-04T13:45:20.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.7.1" }
"0.8.0" = { created_at = 2020-02-28T08:04:56.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.8.0" }
"0.9.0" = { created_at = 2020-04-29T10:46:00.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.9.0" }
"0.10.0" = { created_at = 2020-06-10T14:05:49.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.10.0" }
"0.11.0" = { created_at = 2020-07-24T14:48:57.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.11.0" }
"0.12.0" = { created_at = 2020-08-27T14:44:13.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.12.0" }
"0.12.1" = { created_at = 2020-09-16T06:59:05.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.12.1" }
"0.13.0" = { created_at = 2020-09-30T17:58:20.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.13.0" }
"0.13.1" = { created_at = 2020-10-21T08:09:05.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.13.1" }
"0.14.0" = { created_at = 2020-11-16T13:53:41.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.14.0" }
"0.15.0" = { created_at = 2020-12-17T10:33:50.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.15.0" }
"0.16.0" = { created_at = 2021-02-09T08:14:33.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.16.0" }
"0.17.0" = { created_at = 2021-03-12T06:00:19.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.17.0" }
"0.17.1" = { created_at = 2021-03-31T06:48:13.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.17.1" }
"0.17.2" = { created_at = 2021-04-12T21:56:48.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.17.2" }
"0.18.0" = { created_at = 2021-04-26T17:12:41.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.18.0" }
"0.19.0" = { created_at = 2021-06-08T10:33:54.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.19.0" }
"0.19.1" = { created_at = 2021-06-29T12:25:47.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.19.1" }
"0.20.0" = { created_at = 2021-07-14T08:07:49.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.20.0" }
"0.21.0" = { created_at = 2021-10-06T07:31:08.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.21.0" }
"0.22.0" = { created_at = 2022-02-01T12:34:30.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.22.0" }
"0.23.0" = { created_at = 2022-03-09T12:32:37.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.23.0" }
"0.23.1" = { created_at = 2022-03-25T11:16:35.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.23.1" }
"0.24.0" = { created_at = 2022-06-07T09:47:48.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.24.0" }
"0.25.0" = { created_at = 2022-07-21T17:14:32.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.25.0" }
"0.26.0" = { created_at = 2022-09-02T14:17:41.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.26.0" }
"0.24.1" = { created_at = 2022-10-07T17:54:07.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.24.1" }
"0.27.0" = { created_at = 2022-10-11T12:04:58.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.27.0" }
"0.25.1" = { created_at = 2022-10-31T10:48:12.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.25.1" }
"0.26.1" = { created_at = 2022-11-08T12:19:14.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.26.1" }
"0.28.0" = { created_at = 2022-11-24T13:41:17.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.28.0" }
"0.29.0" = { created_at = 2023-01-05T14:46:03.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.29.0" }
"0.29.1" = { created_at = 2023-02-02T08:53:27.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.29.1" }
"0.30.0" = { created_at = 2023-03-27T07:13:43.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.30.0" }
"0.30.1" = { created_at = 2023-04-10T15:48:43.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.30.1" }
"0.31.0" = { created_at = 2023-05-10T04:57:03.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.31.0" }
"0.31.1" = { created_at = 2023-06-13T13:43:15.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.31.1" }
"0.31.2" = { created_at = 2023-08-01T15:11:53.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.31.2" }
"0.32.0" = { created_at = 2023-09-08T05:20:32.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.32.0" }
"0.32.1" = { created_at = 2023-10-18T20:58:48.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.32.1" }
"0.30.2" = { created_at = 2023-10-20T17:00:10.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.30.2" }
"0.31.3" = { created_at = 2023-10-20T14:33:32.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.31.3" }
"0.32.2" = { created_at = 2023-10-20T07:40:35.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.32.2" }
"0.33.0" = { created_at = 2023-11-09T16:34:34.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.33.0" }
"0.34.0" = { created_at = 2024-01-11T11:20:32.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.34.0" }
"0.35.0" = { created_at = 2024-02-07T14:55:11.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.35.0" }
"0.35.1" = { created_at = 2024-02-13T12:16:46.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.35.1" }
"0.36.0" = { created_at = 2024-03-20T12:45:30.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.36.0" }
"0.35.2" = { created_at = 2024-03-25T12:43:41.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.35.2" }
"0.37.0" = { created_at = 2024-05-13T08:45:16.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.0" }
"0.38.0" = { created_at = 2024-08-21T13:18:52.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.38.0" }
"0.38.1" = { created_at = 2024-09-10T11:45:02.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.38.1" }
"0.39.0" = { created_at = 2024-11-26T10:06:07.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.39.0" }
"0.38.2" = { created_at = 2025-01-30T15:29:21.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.38.2" }
"0.39.1" = { created_at = 2025-01-30T19:20:05.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.39.1" }
"0.35.3" = { created_at = 2025-02-10T05:55:15.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.35.3" }
"0.37.1" = { created_at = 2025-02-10T03:20:26.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.1" }
"0.40.0" = { created_at = 2025-02-26T03:19:34.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.40.0" }
"0.41.0" = { created_at = 2025-05-20T13:23:46.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.41.0" }
"0.41.1" = { created_at = 2025-07-14T09:29:16.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.41.1" }
"0.42.0" = { created_at = 2025-08-21T15:00:19.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.42.0" }
"0.43.0" = { created_at = 2025-11-20T13:00:51.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.43.0" }
"0.37.2" = { created_at = 2026-01-16T06:15:28.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.2" }
"0.42.1" = { created_at = 2026-02-09T09:26:39.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.42.1" }
"0.37.3" = { created_at = 2026-02-18T12:25:52.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.3" }
"0.44.0" = { created_at = 2026-02-23T13:51:27.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.44.0" }
"0.43.1" = { created_at = 2026-03-10T13:25:05.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.43.1" }
"0.37.4" = { created_at = 2026-03-20T03:55:08.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.4" }
"0.44.1" = { created_at = 2026-04-07T05:01:52.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.44.1" }
"0.37.5" = { created_at = 2026-04-10T06:07:00.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.5" }
"0.37.6" = { created_at = 2026-04-20T07:07:03.000Z, release_url = "https://github.com/tektoncd/cli/releases/tag/v0.37.6" }
