[versions]
"2.3.1" = { created_at = 2025-09-28T18:18:30.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.3.1" }
"2.3.2" = { created_at = 2025-09-29T11:28:14.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.3.2" }
"2.4.0" = { created_at = 2025-10-21T15:48:40.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.4.0" }
"2.5.0" = { created_at = 2025-10-25T11:47:23.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.5.0" }
"2.5.1" = { created_at = 2025-10-26T12:45:00.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.5.1" }
"2.5.2" = { created_at = 2025-10-31T21:28:18.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.5.2" }
"2.6.0" = { created_at = 2025-11-02T15:38:47.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.6.0" }
"2.7.0" = { created_at = 2025-11-11T13:55:16.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.7.0" }
"2.8.0" = { created_at = 2025-11-12T23:20:57.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.8.0" }
"2.9.0" = { created_at = 2025-12-03T23:15:18.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.9.0" }
"2.10.0" = { created_at = 2025-12-19T05:04:24.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.10.0" }
"2.11.0" = { created_at = 2025-12-31T01:14:06.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.11.0" }
"2.12.0" = { created_at = 2026-01-14T17:48:16.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.12.0" }
"2.13.0" = { created_at = 2026-01-19T04:31:36.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.13.0" }
"2.13.1" = { created_at = 2026-01-19T05:37:59.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.13.1" }
"2.14.0" = { created_at = 2026-01-26T02:10:59.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.14.0" }
"2.15.0" = { created_at = 2026-01-26T16:01:17.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.15.0" }
"2.15.1" = { created_at = 2026-01-28T15:27:16.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.15.1" }
"2.16.0" = { created_at = 2026-01-29T12:08:21.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.16.0" }
"2.16.1" = { created_at = 2026-01-31T11:52:07.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.16.1" }
"2.16.2" = { created_at = 2026-02-12T00:54:06.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.16.2" }
"2.17.0" = { created_at = 2026-02-16T23:10:09.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.17.0" }
"2.17.4" = { created_at = 2026-02-18T14:17:11.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.17.4" }
"2.18.0" = { created_at = 2026-02-18T14:46:52.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.18.0" }
"2.18.1" = { created_at = 2026-02-24T23:36:46.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.18.1" }
"2.18.2" = { created_at = 2026-03-01T22:44:08.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v2.18.2" }
"3.0.0" = { created_at = 2026-03-13T14:55:22.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v3.0.0" }
"3.1.0" = { created_at = 2026-03-22T16:45:57.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v3.1.0" }
"3.2.0" = { created_at = 2026-03-23T18:31:33.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v3.2.0" }
"3.2.1" = { created_at = 2026-04-22T01:32:31.000Z, release_url = "https://github.com/jdx/usage/releases/tag/v3.2.1" }
