[versions]
"0.1.3" = { created_at = 2018-05-29T06:51:04.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.1.3" }
"0.1.4" = { created_at = 2018-05-30T22:43:28.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.1.4" }
"0.2.0" = { created_at = 2018-09-15T17:53:03.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.2.0" }
"0.2.1" = { created_at = 2018-09-16T22:08:29.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.2.1" }
"0.2.2" = { created_at = 2020-01-31T22:16:49.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.2.2" }
"0.3.0" = { created_at = 2020-06-12T17:52:51.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.3.0" }
"0.3.1" = { created_at = 2020-06-13T16:07:01.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.3.1" }
"0.3.2" = { created_at = 2020-06-28T13:05:51.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.3.2" }
"0.5.0-wip2" = { created_at = 2022-02-02T20:24:04.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.5.0-wip2", prerelease = true }
"0.4.0" = { created_at = 2022-03-03T11:06:59.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.4.0" }
"0.5.0" = { created_at = 2022-06-24T14:07:24.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.5.0" }
"0.4.1" = { created_at = 2022-07-19T14:17:13.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.4.1" }
"0.5.2" = { created_at = 2022-07-19T13:46:05.000Z, release_url = "https://github.com/MaybeJustJames/zephyr/releases/tag/v0.5.2" }
