name: python-precompiled
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: python-precompiled
  cancel-in-progress: true

permissions:
  contents: write

env:
  GITHUB_API_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MISE_GITHUB_TOKEN }}
  DRY_RUN: 0
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: npm install
      - run: ./scripts/python.sh
      - name: Upload .gz files to R2
        run: ./scripts/upload-gz.sh
        env:
          API_URL: https://mise-versions.jdx.dev
          API_SECRET: ${{ secrets.TOKEN_MANAGER_SECRET }}
