name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: bun install
      - run: bun install --cwd web
      - run: npm run build -w web
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: bun install
      - run: bun install --cwd web
      - run: hk check
